# Generated by Django 2.2.28 on 2023-05-26 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_hi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hello',
        ),
    ]
